
# To run self hosted on ubuntu 20.04: apt install build-essential

name: Continues Delivery

on:
     push:
     pull_request:

jobs:
     testUsingServer:
          runs-on: self-hosted
          steps:
               - name: 'Cleanup build folder'
                 run: |
                    ls -la ./
                    rm -rf ./* || true
                    rm -rf ./.??* || true
                    ls -la ./
               - uses: actions/checkout@v3
               - name: Use Node.js 12.x
                 uses: actions/setup-node@v3
                 with:
                    node-version: 12.x
                    cache: 'npm'
               - name: Use Python 2.7
                 uses: actions/setup-python@v3
                 with:
                    python-version: 2.7
                 env:
                    PYTHON_VERSION: 2.7
               - run: npm ci
               - run: npm i screeps@4.2.14 ncp@^2.0.0 q@^1.5.1 dotenv@^16.0.1 screeps-api@1.16.0 screepsmod-admin-utils@1.28.1 screepsmod-auth@2.6.2
               - run: npm run build
               - name: Execute server
                 run: node server/index.js 600
                 env:
                   STEAM_API_KEY: ${{ secrets.API_KEY }}
                   STEAM_ID: ${{ secrets.STEAM_ID }}
