
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# npm i ncp@^2.0.0 q@^1.5.1  screeps@4.2.14 dotenv@^16.0.1 screeps-api@1.16.0 screepsmod-admin-utils@1.28.1 screepsmod-auth@2.6.2 -g

name: Continues Delivery

on:
     push:
     pull_request:

jobs:
     testUsingServer:
          runs-on: self-hosted
          steps:
               - uses: actions/checkout@v3
               - run: npm ci
               - run: npm i isolated-vm
               - run: npm i ncp@^2.0.0 
               - run: npm i q@^1.5.1
               - run: npm i screeps@4.2.14
               - run: npm i dotenv@^16.0.1
               - run: npm i screeps-api@1.16.0 
               - run: npm i screepsmod-admin-utils@1.28.1 
               - run: npm i screepsmod-auth@2.6.2
               - run: set BUILD_MINUTES=60
               - run: npm run test-server
